name: Robô Rastreador (Playwright)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coletar-e-salvar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar código
        uses: actions/checkout@v3

      - name: 2. Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar bibliotecas e Navegadores
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: 4. Executar Robô
        run: python scraper.py

      - name: 5. Salvar mudanças (CSV e Foto)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualização e Debug"
          # AQUI: Adicionei *.png para ele salvar a foto
          file_pattern: "*.csv *.png"
