name: Robô Rastreador

on:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6h
  workflow_dispatch:      # Permite rodar no botão manual

permissions:
  contents: write

jobs:
  coletar-e-salvar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar código
        uses: actions/checkout@v3

      - name: 2. Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: 4. Executar Robô
        run: python scraper.py

      - name: 5. Salvar mudanças automaticamente
        # Esta Action pronta evita o erro 128 e o erro de pathspec
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualização Automática de Preços"
          file_pattern: "*.csv"
